### ISSUE TITLE
Event `token`: Cannot read property `items` of undefined

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-web#1]
Steps to reproduce
- Insert token to slot
- Select token
- Remove token from slot

There is no error if do insert/remove token with selected system provider

![image](https://user-images.githubusercontent.com/7333669/30644446-13b7d210-9e1b-11e7-9e7d-28d12db89715.png)

**Comment by donskov** [comment]
@microshine Fixed. Please check
