### ISSUE TITLE
Spanish: "Grabando log" -> “Gestionar Log”

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify-web#18]

**Comment by rmhrisk** [comment]
Seems this might be in another part of the project, this is the enable logging context menu item.

**Comment by thidalgosalvador** [comment]
Hi,
In Spanish, this option should appear as "**Gestionar Log**" since there are two options related to logs; activation and viewing.

![image](https://user-images.githubusercontent.com/34691149/35183952-a8dd5472-fdee-11e7-914f-ec8795c8b3b4.png)

Thanks!

**Comment by thidalgosalvador** [comment]
In Versión: 1.0.13, the translation is now correct.
![image](https://user-images.githubusercontent.com/34691149/35456439-b8f6d0cc-02d5-11e8-93be-5ba866786693.png)

This issuer can go into closed state.
