### ISSUE TITLE
Add a new FAQs to Fortify web page

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify-web#22]
**What are the privacy implications of using Fortify?**
Websites that you visit will be able to discover that you are running Fortify and this might be useful when combined with other information your browser leaks to track you on the web. These websites will not be able to tell what certificates, or smart cards you have unless you authorize them.

Once you authorize a website it will be able to see what certificates you have, with that information they may be able to infer other information about you. For example, if your certificates contain your legal name, they will have access to that information or if you have a national id card with a certificate it may be able to infer your citizenship.

**What are the security implications of using Fortify?**
We have gone out of our way to try to make Fortify a secure solution. We do believe the solution is well designed and resilient but to err is human so we expect to have security issues to resolve in the future.

With that said, the nature of the feature goals of Fortify requires it to enable websites to interact with the X.509 certificates and their associated cryptographic keys. This means when you grant these websites access to use Fortify they will have an opportunity to use those certificates and keys.

For smart cards Fortify will only let you use certificates that require a pin on use, it also has a unique session to the smart card per website so you will be prompted for use.

For software protected keys however if the software implementation does not require a prompt or pin on use the website will be able to use the associated key without explicit consent. 

You should also be mindful if a website uses Fortify, any third-party origins the website incorporates will also be able to use Fortify.

**How do I decide what websites I should let use Fortify**
You should only let websites use Fortify that you trust, this is because they may be able to track you (like a cookie) and potentially trick you into signing something with a cryptographic key you control.

**Comment by donskov** [comment]
Added

![image](https://user-images.githubusercontent.com/9417251/85267161-8bf19b00-b47d-11ea-94c9-4d4de5ff5daa.png)
