### ISSUE TITLE
Update certificate view to be consistent with certnod

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify-web#23]
You made some improvements to the certificate view, they should find their way back here.

**Comment by rmhrisk** [comment]
Lets make the big values (key, etc) expandable here also.

We really should have these as re-usable components.

**Comment by rmhrisk** [comment]
@YuryStrozhevsky I think viewing certificate contents is a common enough scenario maybe instead of having each application build this decoding logic it might make sense to improve toJson in PKIjs so that a UI can just display values vs worry about ASN.1.

**Comment by YuryStrozhevsky** [comment]
Not sure - what exactly you want from PKIJS?

**Comment by rmhrisk** [comment]
I think we could make the ToJson method provide something more consumable by web developers to build things like this certificate view.

**Comment by YuryStrozhevsky** [comment]
@rmhrisk Yes, I got that you think about re-design of `toJSON` method. I mean how exactly outcome should looks like?

**Comment by donskov** [comment]
Now we use this [code](https://github.com/PeculiarVentures/fortify-web/blob/master/src/helpers/cert_helper.js#L221-L355) for parse certificate content. Will be nice remove this code and use only `toJSON` method.

### Extensions

Now extensions (for example `2.5.29.19`) looks like:

![image](https://user-images.githubusercontent.com/9417251/39746607-7ef0da66-52b3-11e8-8948-ea788a6bebdd.png)

Expected:

![image](https://user-images.githubusercontent.com/9417251/39746651-a45f1092-52b3-11e8-9b5c-e2b4a32558bb.png)

Will be nice decode oid too.

For multiple `value`:

![image](https://user-images.githubusercontent.com/9417251/39746735-ec053458-52b3-11e8-8813-001848a780e8.png)

### Issuer

After `toJSON`:

![image](https://user-images.githubusercontent.com/9417251/39746820-33f3af56-52b4-11e8-9217-74f484d7d259.png)

Expected:

![image](https://user-images.githubusercontent.com/9417251/39746850-493495b0-52b4-11e8-8979-dd9bb4c96037.png)

### Subject

![image](https://user-images.githubusercontent.com/9417251/39746895-6ee9188a-52b4-11e8-9d98-b21a04be94bc.png)

Expected:

![image](https://user-images.githubusercontent.com/9417251/39746911-7a58362e-52b4-11e8-8f06-d81bd3c791ad.png)

### Public Key

Expected:

![image](https://user-images.githubusercontent.com/9417251/39746979-aa21528c-52b4-11e8-8333-cdb20c633c6e.png)

### Signature

Expected:

![image](https://user-images.githubusercontent.com/9417251/39747040-d3539002-52b4-11e8-8075-c7a3d06310f7.png)

### Basic information

Expected:

![image](https://user-images.githubusercontent.com/9417251/39747126-112d9c60-52b5-11e8-9dfe-f25574695b1a.png)

### Fingerprint

Expected `SHA-256` and `SHA-1` values

### Other data

Will be nice to have keys: `isRoot`, `isCA` and `pem` value

@YuryStrozhevsky Ready for discussion

**Comment by YuryStrozhevsky** [comment]
@donskov Just one question - why you call the `toJSON` method? You have `certificate` (having type `Object`) as input and produces another `Object` as output, very different from output of `toJSON`. Why not just work with initial `certificate` directly?

**Comment by donskov** [comment]
@YuryStrozhevsky You are right. Using `toJSON ` method not necessary and it be removed from [this](https://github.com/PeculiarVentures/fortify-web/blob/master/src/helpers/cert_helper.js#L221-L355) code
