### ISSUE TITLE
Disable `Create new` button for read only providers

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-web#3]
```js
ws.info()
  .then(info => console.log(info))
  .catch((err) => {console.log(err)})
```

![image](https://user-images.githubusercontent.com/7333669/33349235-5753fede-d4aa-11e7-810f-281a836bfb22.png)

**Comment by donskov** [comment]
@microshine It works now. Please check

**Comment by microshine** [comment]
It's ok

To emulate this behavior for your SafeNET iKey 2032 you must to update `~/.fortify/card.json`.

```json
{
  "atr": "3bff1100008131fe4d8025a00000005657444b3333300600d0",
  "name": "Datakey 32K PKI Smart Card Model 330",
  "readOnly": true,
  "driver": "39b3d7a3662c4b48bb120d008dd18648"
}
```

I've got small issue about button styles

### Disabled
![image](https://user-images.githubusercontent.com/7333669/33483532-5026ac86-d6af-11e7-8101-f50f464b6adc.png)

### Enabled
![image](https://user-images.githubusercontent.com/7333669/33483775-740efb20-d6b0-11e7-94dc-51a6402eb909.png)

I guess grayscale icon for button will be better

**Comment by donskov** [comment]
@microshine Ok, I will do it

**Comment by donskov** [comment]
@microshine Please check result

**Comment by microshine** [comment]
It's working
