### ISSUE TITLE
Update behavior on token events

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify-web#4]
I'm updating Fortify. New version can return more than 1 info about added or removed tokens. Current version of UI shows only 1 item from the list

### After 2 tokens insertion
![image](https://user-images.githubusercontent.com/7333669/33613311-5f0c4376-d9e5-11e7-82f6-e4ace318c75a.png)

```
Provider:Token Amount of tokens was changed (+2/-0)
```

### After window refreshing
![image](https://user-images.githubusercontent.com/7333669/33613411-9d24f0a4-d9e5-11e7-9cad-701b6a29f762.png)

@donskov if you need updated Fortify version let me know about it

**Comment by donskov** [comment]
@microshine I deployed new version. Please check result

**Comment by microshine** [comment]
@donskov Thank you!!! It's ok
