### ISSUE TITLE
Server is offline.  Wait until the connection is established

### ISSUE THREAD

**Issue by hedibox** [PeculiarVentures/fortify-web#40]
Hello,

After running fortify-web with npm run start, the server run but i always have on start the dialog modal with "Server is offline.  Wait until the connection is established",
how i can fix that to run fortify properly,

thanks,

**Comment by donskov** [comment]
@hedibox Thank you for the issue!
For resolve this I need more information:
1. Fortfiy application version  (click `About` and copy version)
2. The browser name you are working in

**Comment by hedibox** [comment]
**Tag:** 1.0.20 (dev mode)  
**Browser:** Chrome Version 80.0.3987.163 (Build officiel) (64 bits) for the browser

**Comment by donskov** [comment]
Now the actual Fortify version is `1.0.21`. Could you download the application from [official website](https://fortifyapp.com/)? And try to connect with your local `fortify-web`

**Comment by hedibox** [comment]
Is working, 
Thank you !
