### ISSUE TITLE
Error occurs: `Unhandled Rejection (ReferenceError): WebcryptoSocket is not defined`

### ISSUE THREAD

**Issue by sakenomanai** [PeculiarVentures/fortify-web#44]
An error occurs when running fortify-web in my local environment.

1. git clone https://github.com/PeculiarVentures/fortify-web.git
2. npm install
3. npm run start
4. Browser automatically opens http://localhost:3000
   then error occurs on browser

*Enviroment
  Windows10: 
  node version: v12.17.0
  npm version: 6.14.4

![error](https://user-images.githubusercontent.com/19771995/87367468-0eb9d180-c5b6-11ea-86ce-842718b521b9.png)

**Comment by rmhrisk** [comment]
Does your localhost instanced use a SSL session?

**Comment by sakenomanai** [comment]
No, it does not.
my fortify-web server listens http://localhost:3000.

**Comment by donskov** [comment]
Hello @sakenomanai. Could you share your browser console? I think some scripts blocked and need to know why

**Comment by rmhrisk** [comment]
I think your browser is preventing the connection due to lack of SSL,

**Comment by sakenomanai** [comment]
Hello @rmhrisk.
Is this OK ?


![console1](https://user-images.githubusercontent.com/19771995/87485625-2eafca80-c674-11ea-8a4a-dba67f194740.PNG)
![console2](https://user-images.githubusercontent.com/19771995/87485652-44bd8b00-c674-11ea-9404-fa5253fa098a.PNG)
![console3](https://user-images.githubusercontent.com/19771995/87485683-530ba700-c674-11ea-90c2-764d4d07cea4.PNG)

**Comment by rmhrisk** [comment]
@microshine

**Comment by donskov** [comment]
@sakenomanai The app was broken because some scripts blocked and didn't load.
1. Do https://tools.fortifyapp.com works for you?
2. Could you disable AdBlock for localhost:3000?

**Comment by sakenomanai** [comment]
@donskov 
1. Yes, it does.  site https://tools.fortifyapp.com work.
2. I did not install AdBlock into chrome.

**Comment by donskov** [comment]
@sakenomanai 

I tried to clone the repo and install modules again on macOS and Windows and all works.
Please try to:
1. disable VPN (if you have)
2. use another browser
3. use incognito mode

The problem is that your environment blocks scripts.

Thanks!

**Comment by sakenomanai** [comment]
@donskov

i do not use VPN.
> 1. disable VPN (if you have)

same error occurs on windows10 edge, firefox
> 2. use another browser

same error occurs on incognito mode of windows10 and Mac chrome
> 3. use incognito mode


i tried to clone and install modules on mac os. same error occurs on chrome safari.

Do you type commands according to the following procedure ?

1. git clone https://github.com/PeculiarVentures/fortify-web.git
2. npm install
3. npm run start

**Comment by donskov** [comment]
@sakenomanai 

Yes, I do the same way.

I updated the scripts path and pushed to the master https://github.com/PeculiarVentures/fortify-web/commit/5ea973dad8d59115cbe4a81d99e3e5ae3adfa4ba

Please try to pull and `npm run start` again.

**Comment by sakenomanai** [comment]
Hello @donskov and @rmhrisk.

I tried to pull master 5ea973d, install modules and run start
http://localhost:3000 works on both windows os and mac os !

Thank you so much for all your help.
